#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, ordered by occurrence count

awk '{print $1, $9}' apache-access.log | awk '{count[$1" "$2]++} END {for (key in count) printf "%7d %s\n", count[key], key}' | sort -rn
