#!/usr/bin/env bash
# Create the PID file
echo $$ > /var/run/myscript.pid

# Define signal handlers
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "Deleting PID file and quitting..."; rm -f /var/run/myscript.pid; exit 0' SIGQUIT
trap 'echo "Deleting PID file and quitting..."; rm -f /var/run/myscript.pid; exit 0' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
